version: '3'
services:
    postgres:
        image: postgres:13.3
        environment:
            POSTGRES_DB: "users_service"
            POSTGRES_USER: "users_service"
            POSTGRES_PASSWORD: "users_service"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - ./docker/pgsql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - users_service-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - users_service
volumes:
    users_service-data:

networks:
    users_service:
        driver: bridge
